# These are all contribution options. They are listed in priority order.
# GitHub will present the most visible link, if all are provided.
# You can uncomment or remove any that you don't want to use.

# github_funding: true  # For GitHub Sponsors
# custom: https://www.paypal.com/paypalme/yourusername
# bronze: https://www.buymeacoffee.com/yourusername
# silver: https://www.buymeacoffee.com/yourusername
# gold: https://www.buymeacoffee.com/yourusername
# open_collective: your_open_collective
# patreon: your_patreon
# consultance: your_consultance_url
# community_bridge: your_community_bridge_url
# github_sponsors:  # For GitHub Sponsors
# ko_fi: your_ko_fi_url
